global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'p2p_extractor_metrics'
    static_configs:
    # "metrics-host" is a name defined in compose.yml. The address is served by metrics-tool.
    - targets: ['metrics-host:9090']
      labels:
        host: my_host

rule_files:
  - "rules/*"
