{
 "title": "Anomalies",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Closed connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_conn_closed_increase_30m",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_conn_closed_increase_30m\"}",
     "legendFormat": "{{}}"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_conn_closed_increase_30m\"}",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_conn_closed_increase_30m\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_conn_closed_increase_30m\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_conn_closed_increase_30m\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_conn_closed_increase_30m\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Total addresses received in Inbound addrv2 msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_addrv2_addresses_sum_inbound_increase_1h\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Total addresses received in Inbound addr msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_p2p_addr_addresses_sum_inbound_increase_1h",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_addr_addresses_sum_inbound_increase_1h\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_conn_inbound_current_anomaly",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_conn_inbound_current_anomaly\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Peers connected via ipv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "peerobserver_rpc_peer_info_network_peers_iv4",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_rpc_peer_info_network_peers_iv4\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Outbound traffic share to LinkingLion peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "peerobserver_p2p_share_linkinglion_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "upper_band{anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lower_band{anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}[2m])\r\n    < bool last_over_time(lower_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}[2m])\r\n)\r\n+\r\n(\r\n    last_over_time(anomaly:adaptive:select{anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}[2m])\r\n    > bool last_over_time(upper_band{anomaly_strategy=\"adaptive\", anomaly_name=\"peerobserver_p2p_share_linkinglion_total\"}[2m])\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  }
 ]
}